services:
  aisstream-backup:
    build:
      context: ./data-sync
      dockerfile: Dockerfile.aisstream
    image: gnawhnehpets/keitracker-2:latest
    restart: unless-stopped
    command: python -u main_aisstream.py
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_COLLECTION=${DATABASE_COLLECTION}
      - AISSTREAM_API_KEY=${AISSTREAM_API_KEY}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
