services:
  data-sync:
    build:
      context: ./data-sync
    image: ${DOCKERHUB_USERNAME}/keitracker:latest
    restart: unless-stopped
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_COLLECTION=${DATABASE_COLLECTION}
      - AISSTREAM_API_KEY=${AISSTREAM_API_KEY}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  api:
    build:
      context: ./api
    image: ${DOCKERHUB_USERNAME}/keitracker-api:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_COLLECTION=${DATABASE_COLLECTION}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - REPO_USER=${DOCKERHUB_USERNAME}
      - REPO_PASS=${DOCKERHUB_TOKEN}
